setup:
  debug: true

# twig setup
twig:
  debug: false
  cache: false

# define module configurations and sometimes classes to be autoloaded
modules:
  # authentication and account handling
  Core\Session:
    timeout: 1800
    authenticators:
      - Account\Yaml\Account
  LifetaskerPlaceholder:
    class: Lifetasker/LifetaskerPlaceholder

# basic site js/css includes
javascript:
  - https://code.jquery.com/jquery-3.3.1.min.js
  - https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js
  - common:*
  - site.js
css:
  - https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
  - common:*
  - site.css
